name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes

  build-upload:
    name: Build and Upload Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            binary: "cbl-lumberjack"
            renamed_binary: "cbl-lumberjack_ubuntu"
          - os: windows-latest
            binary: "cbl-lumberjack.exe"
            renamed_binary: "cbl-lumberjack_windows.exe"
          - os: macos-latest
            binary: "cbl-lumberjack"
            renamed_binary: "cbl-lumberjack_macos"

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust Toolchain
        run: |
          rustup update

      - name: Toolchain Info
        run: cargo --version --verbose && rustup show

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cargo build --release

      - name: Rename Binaries
        working-directory: ${{ github.workspace }}
        run: |
          mv "target/release/${{ matrix.binary }}" "target/release/${{ matrix.renamed_binary }}"

      - name: Upload Binaries
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} --repo="$GITHUB_REPOSITORY" "target/release/${{ matrix.renamed_binary }}"

  delete_release:
    name: Delete Release
    runs-on: ubuntu-latest
    needs: build-upload
    # Disabled until Windows `gh release upload` works.
    if: ${{ !always() }}
    steps:
      - name: Delete Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release delete "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --cleanup-tag \
            -y
